# Generated by Django 4.1.7 on 2023-03-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=230, verbose_name='Название сайта')),
                ('descriptions', models.TextField(verbose_name='Описание сайта')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='Логотип сайта')),
                ('phone', models.CharField(max_length=100, verbose_name='Тел.ном')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('adsress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('instagramm', models.URLField(verbose_name='Instagramm')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройка сайта',
            },
        ),
    ]
